// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/

//     ____  _                ____   ___  _ 
//    / ___|(_)_ __ ___   ___| ___| / _ \/ |
//    \___ \| | '_ ` _ \ / _ \___ \| | | | |
//     ___) | | | | | | | (_) |__) | |_| | |
//    |____/|_|_| |_| |_|\___/____/ \___/|_|
                                          

//@version=5
indicator('S and R highlighter', overlay=true)

sensibility = input(title="Sensibility", defval=20)
source_ = input.source(high, "Price source")

res = ta.highest(source_, sensibility)
supp = ta.lowest(source_, sensibility)

plot(res, "resistance", ta.change(res) ? na : color.green)
plot(supp, "support", ta.change(supp) ? na : color.red)





